"""empty message

Revision ID: 2a1e5304677d
Revises: 
Create Date: 2021-06-13 19:29:54.919846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1e5304677d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Breakfast',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Calories', sa.Float(precision=10), nullable=True),
    sa.Column('Proteins', sa.Float(precision=10), nullable=True),
    sa.Column('Carbohydrates', sa.Float(precision=10), nullable=True),
    sa.Column('Fiber', sa.Float(precision=10), nullable=True),
    sa.Column('Fats', sa.Float(precision=10), nullable=True),
    sa.Column('Cholesterol', sa.Float(precision=10), nullable=True),
    sa.Column('Sodium', sa.Float(precision=10), nullable=True),
    sa.Column('Ingredients', sa.Text(), nullable=True),
    sa.Column('Steps', sa.Integer(), nullable=True),
    sa.Column('Time', sa.Integer(), nullable=True),
    sa.Column('Servings', sa.Integer(), nullable=True),
    sa.Column('AggregatedRating', sa.Integer(), nullable=True),
    sa.Column('ReviewCount', sa.Integer(), nullable=True),
    sa.Column('soup', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('LunchDinner',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Text(), nullable=True),
    sa.Column('Calories', sa.Float(precision=10), nullable=True),
    sa.Column('Proteins', sa.Float(precision=10), nullable=True),
    sa.Column('Carbohydrates', sa.Float(precision=10), nullable=True),
    sa.Column('Fiber', sa.Float(precision=10), nullable=True),
    sa.Column('Fats', sa.Float(precision=10), nullable=True),
    sa.Column('Cholesterol', sa.Float(precision=10), nullable=True),
    sa.Column('Sodium', sa.Float(precision=10), nullable=True),
    sa.Column('Ingredients', sa.Text(), nullable=True),
    sa.Column('Steps', sa.Integer(), nullable=True),
    sa.Column('Time', sa.Integer(), nullable=True),
    sa.Column('Servings', sa.Integer(), nullable=True),
    sa.Column('AggregatedRating', sa.Integer(), nullable=True),
    sa.Column('ReviewCount', sa.Integer(), nullable=True),
    sa.Column('soup', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('disease', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('height', sa.String(length=64), nullable=True),
    sa.Column('weight', sa.String(length=64), nullable=True),
    sa.Column('blood', sa.String(length=64), nullable=True),
    sa.Column('exercise', sa.String(length=64), nullable=True),
    sa.Column('diet_pref', sa.String(length=64), nullable=True),
    sa.Column('plan_period', sa.String(length=64), nullable=True),
    sa.Column('food_type', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_age'), 'users', ['age'], unique=False)
    op.create_index(op.f('ix_users_blood'), 'users', ['blood'], unique=False)
    op.create_index(op.f('ix_users_diet_pref'), 'users', ['diet_pref'], unique=False)
    op.create_index(op.f('ix_users_disease'), 'users', ['disease'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_exercise'), 'users', ['exercise'], unique=False)
    op.create_index(op.f('ix_users_food_type'), 'users', ['food_type'], unique=False)
    op.create_index(op.f('ix_users_height'), 'users', ['height'], unique=False)
    op.create_index(op.f('ix_users_plan_period'), 'users', ['plan_period'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_weight'), 'users', ['weight'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_weight'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_plan_period'), table_name='users')
    op.drop_index(op.f('ix_users_height'), table_name='users')
    op.drop_index(op.f('ix_users_food_type'), table_name='users')
    op.drop_index(op.f('ix_users_exercise'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_disease'), table_name='users')
    op.drop_index(op.f('ix_users_diet_pref'), table_name='users')
    op.drop_index(op.f('ix_users_blood'), table_name='users')
    op.drop_index(op.f('ix_users_age'), table_name='users')
    op.drop_table('users')
    op.drop_table('LunchDinner')
    op.drop_table('Breakfast')
    # ### end Alembic commands ###
